"pages needing transcription" button now fits the kind of project it is.
benwbrum/fromthepage pull request #1939
Opened 2020-08-04 16:17 UTC by JosieBrum

All transcription projects have "pages needing transcription". All correction projects have "pages needing correction". Mixed projects have "pages needing correction or transcription".

2020-10-13 13:27 UTC, saracarl requested changes
Needs I18N

2020-10-13 13:27 UTC, saracarl commented on spec/features/collection_spec.rb
> +    page.click_link("Pages That Need Correction or Transcription")
Can we externalize these messages?  We'll need a way to mark them in the dictionary file as "needing translation" -- maybe with a comment that the translator can remove once it's translated?

2020-10-13 13:27 UTC, saracarl commented on app/views/collection/show.html.slim
> +        =link_to "Pages That Need Transcription", collection_needs_transcription_path(@collection.owner, @collection), class: 'button review-button'
Can we externalize these messages?  We'll need a way to mark them in the dictionary file as "needing translation" -- maybe with a comment that the translator can remove once it's translated?

2020-10-13 13:27 UTC, saracarl commented on app/views/collection/show.html.slim
> +        =link_to "Pages That Need Correction or Transcription", collection_needs_transcription_path(@collection.owner, @collection), class: 'button review-button'
Can we externalize these messages?  We'll need a way to mark them in the dictionary file as "needing translation" -- maybe with a comment that the translator can remove once it's translated?

2020-10-13 13:27 UTC, saracarl commented on app/views/collection/show.html.slim
> +        =link_to "Pages That Need Correction", collection_needs_transcription_path(@collection.owner, @collection), class: 'button review-button'
Can we externalize these messages?  We'll need a way to mark them in the dictionary file as "needing translation" -- maybe with a comment that the translator can remove once it's translated?

2020-10-13 13:27 UTC, saracarl commented on app/views/collection/show.html.slim
> +        =link_to "Pages That Need Transcription", collection_needs_transcription_path(@collection.owner, @collection), class: 'button review-button'
Actually, I think we have an existing message for this one, and maybe for the correction one.

2022-04-13 16:24 UTC, benwbrum commented
Code migrated to PR #3099.  Closing PR.

2022-04-13 16:24 UTC, closed without merging