Added seperation of name and time in notes
benwbrum/fromthepage pull request #2041
Opened 2020-08-31 18:07 UTC by JosieBrum

Looks like this:
![Screenshot (11)](https://user-images.githubusercontent.com/66690740/91751704-d9c80500-eb8a-11ea-88c8-8660d12056f6.png)
If it is not okay, I can figure something else out.

2020-10-06 13:50 UTC, benwbrum commented
@diegoviola said he'd fix the tests for this.

2020-10-13 13:22 UTC, saracarl requested changes

2020-10-13 13:22 UTC, saracarl commented on app/views/notes/_note.html.slim
> -      =" ago"
We seem to have lost the "ago".  Can we add it back in, please?  Translated, if possible.  (Or maybe it's blank in other languages, but it only makes sense in with the "ago" in English.)

2020-10-13 13:45 UTC, benwbrum commented
As @saracarl said, we want the display to say "about 3 years ago" instead of "about 3 years".  We'd like to add `" ago"` and the equivalents in Spanish and Portuguese.

If this requires a new message in the dictionary, we can add a comment saying `# needs translation`

2020-10-19 20:51 UTC, merged