2974 new work field recipient
benwbrum/fromthepage pull request #3080
Opened 2022-04-05 21:49 UTC by sylvieed

2022-04-17 23:57 UTC, sylvieed commented on app/models/work.rb
> +     "recipient",
This adds the `recipient` field to IIIF exports as the export uses the Work's `PUBLIC_ATTRIBUTES` to generate its metadata.

2022-04-18 00:30 UTC, sylvieed commented
The "recipient" field is now included in the following places:

### Work settings page

![work settings](https://user-images.githubusercontent.com/35716893/163737320-43852ad3-8ddd-46f4-b9d9-0893b81e19df.jpg)

### Work about page

![work about](https://user-images.githubusercontent.com/35716893/163737322-265f8c65-e80b-4f79-b492-3bc5b7199f1b.jpg)

### Example `metadata.yml` file

> Recipient -- the recipient of the document, i.e. for a letter or other targeted document

### TEI-XML exports

```
<recipient>
    <persName>Francisco Villarreal</persName>
</recipient>
```

### IIIF exports

```
{
    "label": "Recipient",
    "value": "Francisco Villarreal"
}
```

The work metadata CSV exports doesn't currently have any work-wide metadata (like author, recipient, place of creation) included, so I didn't add it there.

2022-04-18 16:02 UTC, benwbrum requested changes
This all looks spectacular!  Over the course of reviewing, I learned that the TEI XML standard specifies a different way of encoding `recipient`. Rather than adding a tag under `author`, we need a new block in the `profileStmt` specifying a `correspStmt`.

[The `correspStmt` specification](https://cmohge1.github.io/lrbs-digital-editing-intro-2019/TEI-for-Correspondence.pdf) includes a lot of features to support forwarding letters, CCs, and other data modeling items which are beyond our use case.  Rather, if a work has a recipient, we want to assume that it's correspondence and include the sender and recipient in a new `correspStmt` stanza.

So, if the `work.recipient` is not blank, we should add something like this at the beginning of the `profileDesc` element:
```xml
<correspStmt>
  <correspAction type="sent">
    <persName>AUTHOR GOES HERE</persName>
  </correspAction>
  <correspAction type="received">
    <persName>RECIPIENT GOES HERE</persName>
  </correspAction>
</correspStmt>

2022-04-19 23:24 UTC, benwbrum approved these changes
This looks perfect!

2022-04-19 23:26 UTC, sylvieed commented
Here's how the TEI export looks now:

```
<correspDesc>
    <correspAction type="sent">
        <persName>the Laredo Mayor</persName>
    </correspAction>
    <correspAction type="received">
        <persName>Francisco Villarreal</persName>
    </correspAction>
</correspDesc>
```

2022-04-20 13:50 UTC, benwbrum commented
In testing revealed that the `correspDesc` element is nested directly under the `teiHeader` element.  It needs to be nested within the `profileDesc` element instead.

2022-04-20 19:16 UTC, sylvieed commented
Ok, here's where it is now

```
<profileDesc>
    <correspDesc>
        <correspAction type="sent">
            <persName>the Laredo Mayor</persName>
        </correspAction>
        <correspAction type="received">
            <persName>Francisco Villarreal</persName>
        </correspAction>
    </correspDesc>
    <creation>
        <date when="1850-08-17">1850-08-17</date>
    </creation>
    <langUsage>
        <language ident="eng">English</language>
    </langUsage>
</profileDesc>
```

2022-04-20 20:27 UTC, merged