New subject distribution URL and export for #2628
benwbrum/fromthepage pull request #3153
Opened 2022-05-23 01:08 UTC by benwbrum

Subject distribution export is different from subject coocurrence export these ways:

- Limited to a single subject, listing subjects that occur in the same work as that subject
- Lists coocurrences even if they do not appear on the same page, but are on another page in the work
- Aggregated by subject _and work_

2022-05-23 12:52 UTC, saracarl commented
Does this replace the existing subject co occurrence spreadsheet?  If so, I see zero difference between this branch and production for JWG.  If not, shouldn't there be an updated view that includes this?

2022-05-23 12:53 UTC, saracarl requested changes
Does this replace the existing subject co occurrence spreadsheet? If so, I see zero difference between this branch and production for JWG. If not, shouldn't there be an updated view that includes this?

2022-05-26 14:04 UTC, saracarl commented
Test failures:
 
 1) document sets checks document set subject tabs
     Failure/Error: expect(page).to have_content("Description")
       expected to find text "Description" in "NoMethodError at /margaret/test-document-set-1/article/2 T
     # ./spec/features/document_sets_spec.rb:281:in `block (2 levels) in <top (required)>'
  2) subject linking deletes a subject
     Failure/Error: page.find('.tabs').click_link("Settings")
     
     Capybara::ElementNotFound:
       Unable to find css ".tabs"
     # ./spec/features/linking_spec.rb:72:in `block (2 levels) in <top (required)>'

2022-05-31 17:01 UTC, benwbrum commented
This now parses metadata values for works in the spreadsheet.

2022-05-31 18:46 UTC, saracarl commented
Two more issues:
1) After downloading the spreadsheet from the subject page, I get a spinny that never ends.
2) The data is suspect.  I downloaded Big Henry's spreadsheet from JWG, and "Lila" 66604 shows up twice in it with difference counts on each row (1 and then 16).

2022-05-31 20:04 UTC, benwbrum commented
The spinny is a problem.  The data shouldn't be -- each coocurring subject is _per document_, so Lila should have an entry per work she appears in (if Henry also appears in that work).

2022-06-01 16:36 UTC, saracarl approved these changes

2022-06-01 17:01 UTC, merged