#3689-Added Functionality to Sort Based On Transcribed Pages
benwbrum/fromthepage pull request #3719
Opened 2023-07-21 17:32 UTC by symmetrically

2023-07-21 18:31 UTC, saracarl commented
I'm not sure what went wrong here, but there's 2 issues:

1)  The works listed at the top of the collection are 100% transcribed, 0% reviewed.  That's the current functionality, not the desired functionality outlined in the issue which is untranscribed/less transcribed works first.
![image](https://github.com/benwbrum/fromthepage/assets/708566/47a97437-993d-4559-a733-e104a3c7f0e2)

2)  It took forever for my test project to load:
![image](https://github.com/benwbrum/fromthepage/assets/708566/4c13636d-c4d8-42aa-a916-1d676aa18c77)
which implies that something is being calculated.  I think you should be able to get this with an approach along the lines of join_to work_statistics and order_by
(and it definitely shouldn't take this long.)

2023-07-21 18:31 UTC, saracarl requested changes
see comments.

2023-07-24 18:28 UTC, saracarl commented
@symmetrically this is still in the incorrect order.  
![image](https://github.com/benwbrum/fromthepage/assets/708566/d61e5525-96fc-4f15-aefe-0ce185d74ec2)
It's much faster, though.

Here's the collection I'm testing with (on my DB it has a nice spread of completedness):  http://localhost:3000/adah/civil-war-and-reconstruction-governors-of-alabama?page=1
Can you include a screenshot of the results before I review this again?

2023-08-18 16:06 UTC, benwbrum commented
The most recent commit is an improvement, but it does not distinguish between works that are 0% complete _because they have pages that need review_ and works that are 0% complete because they have not been started yet.

See this example of the top of a collection, looking at the percentage statements in the screenshot.
![Screenshot from 2023-08-18 11-03-20](https://github.com/benwbrum/fromthepage/assets/199961/24b47573-7c16-4e42-b237-afda4783d24a)

I suspect that this could be fixed by sorting on two columns instead of one: percentage complete `DESC` (as currently), followed by a count of pages needing review `ASC`.

2023-08-18 19:29 UTC, benwbrum commented
I've recorded a video, which uses a new collection and these sample documents from the Internet Archive:
* https://archive.org/details/cafrmph_000010
* https://archive.org/details/cafrmph_000013
* https://archive.org/details/cafrmph_000112

https://github.com/benwbrum/fromthepage/assets/199961/486cbd0a-ded5-42ae-ae02-b13013f24907

2023-08-24 15:53 UTC, saracarl commented
This will also close #3367

2023-09-14 18:39 UTC, benwbrum requested changes

2023-09-14 18:40 UTC, benwbrum commented on db/migrate/20230821140126_add_transcribed_percentage_to_work_statistics.rb
> +    add_column :work_statistics, :transcribed_percentage, :integer
Once we have the two percentage points, we should sort the list of works based on percent completed (ascending), percent transcribed (ascending) and needs_review_percentage (descending)

2023-09-22 20:20 UTC, merged