4074 - Validate html before saving
benwbrum/fromthepage pull request #4119
Opened 2024-05-22 20:26 UTC by WillNigel23

Based on issue #4074 

Added a reusable html_validator that utilizes `REXML::ParseException` to handle invalid html syntax.

Usage:
```
class YourModel < ApplicationRecord
   validates :your_field, html: true
```

Optionally we can pass specific messages (useful for model-specific translations):
```
class YourModel < ApplicationRecord
   validates :your_field, html: { message: 'Custom error message' }
```

html_validator component can have more features in future such as adding validation for limiting number of characters EXCLUDING html tags so I decided in favor of making it it's own validator class.

2024-05-24 12:55 UTC, saracarl requested changes

2024-05-29 19:28 UTC, WillNigel23 commented on app/models/collection.rb
> +  validates :footer_block, html: { message: 'invalid html syntax' }, length: { maximum: 16.megabytes - 1 }
@saracarl the validation for length is separate from the validation of html, so they will have separate messages

2024-05-31 21:17 UTC, benwbrum commented
One more change came out during testing: `Collection.intro_block` is called `Description` in the UI.  As a result, the error message's reference to "intro block" is confusing.

![Screenshot from 2024-05-31 16-14-00](https://github.com/benwbrum/fromthepage/assets/199961/91cd4c9d-1988-432b-a193-26476911dc67)

In addition, we should validate the work description field using the same rules.

2024-06-03 21:43 UTC, WillNigel23 commented
@benwbrum  @saracarl  ready for review

2024-06-03 21:47 UTC, WillNigel23 commented
Ready for review @benwbrum  @saracarl

2024-06-10 19:37 UTC, WillNigel23 commented
Fix pushed @benwbrum @saracarl

2024-06-14 20:20 UTC, merged