2532 - Assign document set as you move to a collection
benwbrum/fromthepage pull request #4135
Opened 2024-05-28 21:55 UTC by WillNigel23

2024-05-29 17:41 UTC, WillNigel23 commented on app/views/work/edit.html.slim
> +          td#document_sets
We add identifier to the html element whose contents we want to replace. In this case, id: 'document_sets'

2024-05-29 17:41 UTC, WillNigel23 commented on app/views/work/edit.html.slim
> +            documentSetsDiv.html(response);
We fetch to work_document_sets_select_path, it's response is an html partial. In which case we will be using it's response to replace the contents of our html target

2024-05-29 17:42 UTC, WillNigel23 commented on app/views/work/edit.html.slim
> +            $('#work_document_set_ids').multiSelect();
Re-initialize multiSelect() as it is reloaded to html, and we only initialize on page load at application.js

2024-05-29 17:43 UTC, WillNigel23 commented on app/views/work/edit.html.slim
> +        updateDocumentSetOptions(selectedId);
On collection select change, we pass in the selected id which we will be using as params[:collection_id] for the controller

2024-05-29 17:44 UTC, WillNigel23 commented on app/controllers/work_controller.rb
> +  end
The secret sauce. We have a route that, instead of rendering a full response, will render a partial instead.

2024-05-29 17:45 UTC, WillNigel23 commented
@benwbrum @saracarl  Added comments in my implementation. 

PS:
This, in general, is how turbo_streams work. Instead of writing the js for replacing the dom elements with the response, it handles that automatically. Great tool with lots of application.

2024-06-01 02:13 UTC, benwbrum requested changes
Single change for consistency in the German interface.

2024-06-01 02:13 UTC, benwbrum commented on config/locales/work/work-de.yml
> +      document_sets: Dokumentensätze
The German word we are using for "Documents Sets" is "Dokumentensets"

2024-06-01 02:15 UTC, benwbrum commented
This is tested, and works great.  We only have a single word to change in the German version.

2024-06-07 18:31 UTC, merged