4255 - Error making collection private
benwbrum/fromthepage pull request #4257
Opened 2024-07-31 23:11 UTC by WillNigel23

https://github.com/benwbrum/fromthepage/issues/4255#issuecomment-2261635847

Added additional specs for validations. I suggest we also add tests for each part of model validations in the future.

2024-08-02 16:39 UTC, saracarl requested changes
So I tried this with the original description that caused the problem -- the html with an ampersand -- and I thought we were handling the ampersand in some way.  Looks like we're not?

![image](https://github.com/user-attachments/assets/9828afad-12c1-45c4-a5ce-1d1f11cd2030)

So I'm confused and I feel like there's something missing here.

2024-08-02 19:17 UTC, WillNigel23 commented
Seems like a bug on my end. Will check it out monday

2024-08-05 20:24 UTC, WillNigel23 commented
@saracarl I can't reproduce this error using the provided link you sent to me. Are you certain your branch is up to date?

Also might be worth restarting your local dev server

2024-08-06 13:16 UTC, saracarl approved these changes

2024-08-06 13:17 UTC, merged