4103 - Improve document set settings tab to match collection settings
benwbrum/fromthepage pull request #4283
Opened 2024-08-26 22:46 UTC by WillNigel23

2024-08-28 18:26 UTC, WillNigel23 commented on spec/requests/document_sets_controller_spec.rb
> +end
Ideally, we add all defined routes/functions inside document_sets_controller here. That way we have a clear test on all requests.

2024-08-28 18:27 UTC, WillNigel23 commented on spec/interactors/document_set/update_spec.rb
> +end
Moving business logics to interactors also means we can isolate each specific functionalities into unit tests like this.

2024-08-30 14:46 UTC, saracarl approved these changes
Functionality is good.

2024-09-02 20:01 UTC, benwbrum requested changes
There are enough problems with the translations that I think we should discuss the overall approach.  It looks like we are re-translating from English into DE/ES/FR/PT.  This runs the risk of replacing wording that has been reviewed by native speakers, and which we hope to match, with new machine wording which is more awkward to read, less appropriate for our problem domain, and inconsistent with other wording in the system.

I only flagged a few of the problem messages in my review comments, since it looks like we need to change overall approaches.

2024-09-03 19:30 UTC, WillNigel23 commented
Changes:
1. Translation suggestions applied
2. Added spec (but only warns instead of fail) of commonly mis-translated words for 'work'

@benwbrum @saracarl

2024-09-06 19:34 UTC, benwbrum commented on config/locales/document_sets/document_sets-de.yml
> +      description_message: Die Beschreibung wird auf dem Projektübersichtsbildschirm und dem Projektinfobildschirm angezeigt. Ein gekürzter Teil der Beschreibung wird auf dem Organisations-Startbilds
This seems like a lot of changes -- Projectübersichtsseite (Project overview page) is turned into Projectübersichtbildschirm (Project overview screen).  Also in line 5, `Documentenset` is turned to `Documentensatz`.

2024-09-06 19:37 UTC, benwbrum requested changes
It looks like we still have a lot of new translations here.  I just spot-checked the German and Spanish, but I found enough.

Maybe compare the values in `development` with the values here with the same keys to revert the auto-translations?

2024-09-06 19:37 UTC, benwbrum commented on config/locales/document_sets/document_sets-es.yml
> +      actions: Comportamiento
Similarly, `Acciones` is turned to `Comportamiento`, indicating a retranslation.

2024-12-09 23:01 UTC, benwbrum requested changes
A couple of minor translation issues, but this is really exciting!

2024-12-09 23:01 UTC, benwbrum commented on spec/i18n_spec.rb
> +    let(:incorrect_translations) { ['travail', 'travaux', 'trabalho', 'trabalhos', 'arbeit', 'arbeiten', 'trabajo', 'trabajos'] }
Woo hoo!  Hooray!  I love this!

2024-12-09 23:01 UTC, benwbrum commented on spec/i18n_spec.rb
> +    let(:incorrect_translations) { ['travail', 'travaux', 'trabalho', 'trabalhos', 'arbeit', 'arbeiten', 'trabajo', 'trabajos'] }
Let's add Dokumentensetz to this list, too.

2024-12-13 14:54 UTC, merged