4211 - Adding collaborators refresh list
benwbrum/fromthepage pull request #4349
Opened 2024-09-24 22:17 UTC by WillNigel23

2024-09-24 22:18 UTC, WillNigel23 commented on app/assets/javascripts/plugins/jquery.litebox.js
> +      noclose: false          // Remove close button
added `noclose` for litebox prototype

2024-09-24 22:19 UTC, WillNigel23 commented on app/assets/javascripts/plugins/jquery.litebox.js
> +        }
lines 92-99

If noclose option passed, we do not add closebutton

2024-09-24 22:20 UTC, WillNigel23 commented
The diff on the js seems broken (due to empty spaces I assume?)

I marked with comments the lines that I changed. Sorry in advance :pray: 

@benwbrum @saracarl

2024-09-25 19:21 UTC, saracarl requested changes
Can you do the same thing with collection owners?

2024-10-04 17:10 UTC, benwbrum commented
This works well.

2024-10-04 17:10 UTC, merged