4424 - Feedback on settings update
benwbrum/fromthepage pull request #4456
Opened 2024-12-18 19:47 UTC by WillNigel23

2024-12-30 15:24 UTC, saracarl requested changes
1. The UI for subject categories is broken/wonky:

![image](https://github.com/user-attachments/assets/3c978ce2-9b1e-4e19-872c-7ecd8426dbf0)

2. I changed the title and the URL and received no confirmation.  When I moved on to another tab, it turns out they didn't save.  As far as I can tell, none of the settings are saving at all.

I'll review this again once #2 is fixed.

2025-01-02 22:05 UTC, WillNigel23 commented
Can you please try again? Everything is working locally.

Some things that could have caused the error:
1. This requires some new gems installed. Please run bundle install first before running server
2. As per `1`, this means we need server restart on local development.

2025-01-03 14:50 UTC, saracarl commented
Weird.  The only thing I can figure out that may have happened is there were 2 4424 branches, and I got the older one.  This works great!  I really like it.

2025-01-03 14:51 UTC, saracarl approved these changes

2025-01-03 14:51 UTC, merged